// Code generated by tygo. DO NOT EDIT.

//////////
// source: errors.go
/*
Package core holds the domain types and rules. It imports only the standard
library: no storage, no transport, no logging.
*/

/**
 * ValidationError describes a rejected field.
 */
export interface ValidationError {
	Field: string;
	Reason: string;
}

//////////
// source: match.go

export type Venue = "home" | "away" | "neutral";
export const VenueHome: Venue = "home";
export const VenueAway: Venue = "away";
export const VenueNeutral: Venue = "neutral";
export type MatchStatus = "scheduled" | "in_progress" | "completed";
export const MatchScheduled: MatchStatus = "scheduled";
export const MatchInProgress: MatchStatus = "in_progress";
export const MatchCompleted: MatchStatus = "completed";
/**
 * LineupSlot ties a jersey number to the player wearing it.
 */
export interface LineupSlot {
	jersey: number /* int */;
	playerId: string;
}
/**
 * Lineup is the selected squad for one match.
 */
export interface Lineup {
	starters: LineupSlot[];
	bench: LineupSlot[];
}
export interface Match {
	id?: string;
	clubId?: string;
	teamId?: string;
	seasonId: string;
	opponent: string;
	kickoffAt: string;
	competition: string;
	venue: Venue;
	status: MatchStatus;
	lineup: Lineup;
}

//////////
// source: player.go

export type PlayerStatus = "active" | "inactive";
export const PlayerActive: PlayerStatus = "active";
export const PlayerInactive: PlayerStatus = "inactive";
export interface Player {
	id?: string;
	clubId?: string;
	firstName: string;
	lastName: string;
	dob: string;
	positions: Position[];
	teamIds: string[];
	status: PlayerStatus;
}

//////////
// source: position.go

/**
 * Position is an individual playing position. Thirteen positions cover the
 * fifteen starting jerseys: both locks wear 4 and 5, and both wings wear 11
 * and 14.
 */
export type Position =
	| "loosehead"
	| "hooker"
	| "tighthead"
	| "lock"
	| "blindside"
	| "openside"
	| "number_eight"
	| "scrum_half"
	| "fly_half"
	| "wing"
	| "inside_centre"
	| "outside_centre"
	| "fullback";
export const Loosehead: Position = "loosehead"; // 1
export const Hooker: Position = "hooker"; // 2
export const Tighthead: Position = "tighthead"; // 3
export const Lock: Position = "lock"; // 4, 5
export const Blindside: Position = "blindside"; // 6
export const Openside: Position = "openside"; // 7
export const NumberEight: Position = "number_eight"; // 8
export const ScrumHalf: Position = "scrum_half"; // 9
export const FlyHalf: Position = "fly_half"; // 10
export const Wing: Position = "wing"; // 11, 14
export const InsideCentre: Position = "inside_centre"; // 12
export const OutsideCentre: Position = "outside_centre"; // 13
export const Fullback: Position = "fullback"; // 15
/**
 * PositionGroup is the unit within which players are compared. Comparing a
 * prop's carry count against a winger's is noise, so rankings never cross a
 * group boundary.
 */
export type PositionGroup =
	| "front_row"
	| "second_row"
	| "back_row"
	| "half_backs"
	| "centres"
	| "back_three";
export const FrontRow: PositionGroup = "front_row";
export const SecondRow: PositionGroup = "second_row";
export const BackRow: PositionGroup = "back_row";
export const HalfBacks: PositionGroup = "half_backs";
export const Centres: PositionGroup = "centres";
export const BackThree: PositionGroup = "back_three";

//////////
// source: team.go

/**
 * Team is a squad that plays fixtures — the 1st XV, the Colts, the women's
 * side. Players belong to the club, not to a team, so one player can be in
 * several teams at once.
 */
export interface Team {
	id?: string;
	clubId?: string;
	name: string;
	shortName: string;
	active: boolean;
}
