// Code generated by tygo. DO NOT EDIT.

//////////
// source: catalogue.go

/**
 * EventKind identifies one kind of tagged occurrence. The set is closed and lives
 * here, so a new statistic is a new kind plus a case in a pure function, with
 * nothing in store/ or httpapi/ changing.
 */
export type EventKind =
	| "tackle_made"
	| "tackle_missed"
	| "carry"
	| "linebreak"
	| "defender_beaten"
	| "offload"
	| "clearout"
	| "jackal_won"
	| "turnover_won"
	| "handling_error"
	| "kick"
	| "try"
	| "sub"
	| "scrum_won"
	| "scrum_lost"
	| "scrum_penalty_won"
	| "scrum_penalty_conceded"
	| "lineout_won"
	| "lineout_lost"
	| "throw_not_straight"
	| "maul_from_lineout"
	| "restart_received"
	| "restart_lost"
	| "offside"
	| "ruck_offence"
	| "high_tackle"
	| "not_releasing"
	| "scrum_offence"
	| "foul_play"
	| "yellow_card"
	| "red_card"
	| "conversion_made"
	| "conversion_missed"
	| "penalty_goal"
	| "drop_goal"
	| "opposition_try"
	| "opposition_conversion"
	| "opposition_penalty"
	| "opposition_drop"
	| "period_started"
	| "clock_paused"
	| "clock_resumed"
	| "period_ended"
	| "match_ended"
	| "zone_changed"
	| "void";
/**
 * PLAY — always visible, high frequency. Thirteen kinds is the practical ceiling
 * for tapping without looking, which is why clearout and jackal sit here despite
 * being breakdown events: they are too frequent to hide behind a tab.
 */
export const KindTackleMade: EventKind = "tackle_made";
/**
 * PLAY — always visible, high frequency. Thirteen kinds is the practical ceiling
 * for tapping without looking, which is why clearout and jackal sit here despite
 * being breakdown events: they are too frequent to hide behind a tab.
 */
export const KindTackleMissed: EventKind = "tackle_missed";
/**
 * PLAY — always visible, high frequency. Thirteen kinds is the practical ceiling
 * for tapping without looking, which is why clearout and jackal sit here despite
 * being breakdown events: they are too frequent to hide behind a tab.
 */
export const KindCarry: EventKind = "carry";
/**
 * PLAY — always visible, high frequency. Thirteen kinds is the practical ceiling
 * for tapping without looking, which is why clearout and jackal sit here despite
 * being breakdown events: they are too frequent to hide behind a tab.
 */
export const KindLinebreak: EventKind = "linebreak";
/**
 * PLAY — always visible, high frequency. Thirteen kinds is the practical ceiling
 * for tapping without looking, which is why clearout and jackal sit here despite
 * being breakdown events: they are too frequent to hide behind a tab.
 */
export const KindDefenderBeaten: EventKind = "defender_beaten";
/**
 * PLAY — always visible, high frequency. Thirteen kinds is the practical ceiling
 * for tapping without looking, which is why clearout and jackal sit here despite
 * being breakdown events: they are too frequent to hide behind a tab.
 */
export const KindOffload: EventKind = "offload";
/**
 * PLAY — always visible, high frequency. Thirteen kinds is the practical ceiling
 * for tapping without looking, which is why clearout and jackal sit here despite
 * being breakdown events: they are too frequent to hide behind a tab.
 */
export const KindClearout: EventKind = "clearout";
/**
 * PLAY — always visible, high frequency. Thirteen kinds is the practical ceiling
 * for tapping without looking, which is why clearout and jackal sit here despite
 * being breakdown events: they are too frequent to hide behind a tab.
 */
export const KindJackalWon: EventKind = "jackal_won";
/**
 * PLAY — always visible, high frequency. Thirteen kinds is the practical ceiling
 * for tapping without looking, which is why clearout and jackal sit here despite
 * being breakdown events: they are too frequent to hide behind a tab.
 */
export const KindTurnoverWon: EventKind = "turnover_won";
/**
 * PLAY — always visible, high frequency. Thirteen kinds is the practical ceiling
 * for tapping without looking, which is why clearout and jackal sit here despite
 * being breakdown events: they are too frequent to hide behind a tab.
 */
export const KindHandlingError: EventKind = "handling_error";
/**
 * PLAY — always visible, high frequency. Thirteen kinds is the practical ceiling
 * for tapping without looking, which is why clearout and jackal sit here despite
 * being breakdown events: they are too frequent to hide behind a tab.
 */
export const KindKick: EventKind = "kick";
/**
 * PLAY — always visible, high frequency. Thirteen kinds is the practical ceiling
 * for tapping without looking, which is why clearout and jackal sit here despite
 * being breakdown events: they are too frequent to hide behind a tab.
 */
export const KindTry: EventKind = "try";
/**
 * PLAY — always visible, high frequency. Thirteen kinds is the practical ceiling
 * for tapping without looking, which is why clearout and jackal sit here despite
 * being breakdown events: they are too frequent to hide behind a tab.
 */
export const KindSub: EventKind = "sub";
/**
 * SET PIECE — occurs at natural stoppages, where one extra tap is affordable.
 */
export const KindScrumWon: EventKind = "scrum_won";
/**
 * SET PIECE — occurs at natural stoppages, where one extra tap is affordable.
 */
export const KindScrumLost: EventKind = "scrum_lost";
/**
 * SET PIECE — occurs at natural stoppages, where one extra tap is affordable.
 */
export const KindScrumPenaltyWon: EventKind = "scrum_penalty_won";
/**
 * SET PIECE — occurs at natural stoppages, where one extra tap is affordable.
 */
export const KindScrumPenaltyConceded: EventKind = "scrum_penalty_conceded";
/**
 * SET PIECE — occurs at natural stoppages, where one extra tap is affordable.
 */
export const KindLineoutWon: EventKind = "lineout_won";
/**
 * SET PIECE — occurs at natural stoppages, where one extra tap is affordable.
 */
export const KindLineoutLost: EventKind = "lineout_lost";
/**
 * SET PIECE — occurs at natural stoppages, where one extra tap is affordable.
 */
export const KindThrowNotStraight: EventKind = "throw_not_straight";
/**
 * SET PIECE — occurs at natural stoppages, where one extra tap is affordable.
 */
export const KindMaulFromLineout: EventKind = "maul_from_lineout";
/**
 * SET PIECE — occurs at natural stoppages, where one extra tap is affordable.
 */
export const KindRestartReceived: EventKind = "restart_received";
/**
 * SET PIECE — occurs at natural stoppages, where one extra tap is affordable.
 */
export const KindRestartLost: EventKind = "restart_lost";
/**
 * DISCIPLINE — the two cards have side effects in the fold: without them minutes
 * played silently lies, and every per-80 rate built on it lies too.
 */
export const KindOffside: EventKind = "offside";
/**
 * DISCIPLINE — the two cards have side effects in the fold: without them minutes
 * played silently lies, and every per-80 rate built on it lies too.
 */
export const KindRuckOffence: EventKind = "ruck_offence";
/**
 * DISCIPLINE — the two cards have side effects in the fold: without them minutes
 * played silently lies, and every per-80 rate built on it lies too.
 */
export const KindHighTackle: EventKind = "high_tackle";
/**
 * DISCIPLINE — the two cards have side effects in the fold: without them minutes
 * played silently lies, and every per-80 rate built on it lies too.
 */
export const KindNotReleasing: EventKind = "not_releasing";
/**
 * DISCIPLINE — the two cards have side effects in the fold: without them minutes
 * played silently lies, and every per-80 rate built on it lies too.
 */
export const KindScrumOffence: EventKind = "scrum_offence";
/**
 * DISCIPLINE — the two cards have side effects in the fold: without them minutes
 * played silently lies, and every per-80 rate built on it lies too.
 */
export const KindFoulPlay: EventKind = "foul_play";
/**
 * DISCIPLINE — the two cards have side effects in the fold: without them minutes
 * played silently lies, and every per-80 rate built on it lies too.
 */
export const KindYellowCard: EventKind = "yellow_card";
/**
 * DISCIPLINE — the two cards have side effects in the fold: without them minutes
 * played silently lies, and every per-80 rate built on it lies too.
 */
export const KindRedCard: EventKind = "red_card";
/**
 * SCORE — a try alone cannot produce a scoreboard, so the kicks and the
 * opposition's scores are here. They render as a strip beside the score rather
 * than a fourth tab, because they happen at stoppages and the tabs are full.
 */
export const KindConversionMade: EventKind = "conversion_made";
/**
 * SCORE — a try alone cannot produce a scoreboard, so the kicks and the
 * opposition's scores are here. They render as a strip beside the score rather
 * than a fourth tab, because they happen at stoppages and the tabs are full.
 */
export const KindConversionMissed: EventKind = "conversion_missed";
/**
 * SCORE — a try alone cannot produce a scoreboard, so the kicks and the
 * opposition's scores are here. They render as a strip beside the score rather
 * than a fourth tab, because they happen at stoppages and the tabs are full.
 */
export const KindPenaltyGoal: EventKind = "penalty_goal";
/**
 * SCORE — a try alone cannot produce a scoreboard, so the kicks and the
 * opposition's scores are here. They render as a strip beside the score rather
 * than a fourth tab, because they happen at stoppages and the tabs are full.
 */
export const KindDropGoal: EventKind = "drop_goal";
/**
 * SCORE — a try alone cannot produce a scoreboard, so the kicks and the
 * opposition's scores are here. They render as a strip beside the score rather
 * than a fourth tab, because they happen at stoppages and the tabs are full.
 */
export const KindOppositionTry: EventKind = "opposition_try";
/**
 * SCORE — a try alone cannot produce a scoreboard, so the kicks and the
 * opposition's scores are here. They render as a strip beside the score rather
 * than a fourth tab, because they happen at stoppages and the tabs are full.
 */
export const KindOppositionConversion: EventKind = "opposition_conversion";
/**
 * SCORE — a try alone cannot produce a scoreboard, so the kicks and the
 * opposition's scores are here. They render as a strip beside the score rather
 * than a fourth tab, because they happen at stoppages and the tabs are full.
 */
export const KindOppositionPenalty: EventKind = "opposition_penalty";
/**
 * SCORE — a try alone cannot produce a scoreboard, so the kicks and the
 * opposition's scores are here. They render as a strip beside the score rather
 * than a fourth tab, because they happen at stoppages and the tabs are full.
 */
export const KindOppositionDrop: EventKind = "opposition_drop";
/**
 * CONTROL — the clock and the log's own bookkeeping. No buttons on a tab.
 * The clock is driven by these events rather than by device state, so it survives
 * a reload and two coaches tagging one match agree on it without a merge rule.
 */
export const KindPeriodStarted: EventKind = "period_started";
/**
 * CONTROL — the clock and the log's own bookkeeping. No buttons on a tab.
 * The clock is driven by these events rather than by device state, so it survives
 * a reload and two coaches tagging one match agree on it without a merge rule.
 */
export const KindClockPaused: EventKind = "clock_paused";
/**
 * CONTROL — the clock and the log's own bookkeeping. No buttons on a tab.
 * The clock is driven by these events rather than by device state, so it survives
 * a reload and two coaches tagging one match agree on it without a merge rule.
 */
export const KindClockResumed: EventKind = "clock_resumed";
/**
 * CONTROL — the clock and the log's own bookkeeping. No buttons on a tab.
 * The clock is driven by these events rather than by device state, so it survives
 * a reload and two coaches tagging one match agree on it without a merge rule.
 */
export const KindPeriodEnded: EventKind = "period_ended";
/**
 * CONTROL — the clock and the log's own bookkeeping. No buttons on a tab.
 * The clock is driven by these events rather than by device state, so it survives
 * a reload and two coaches tagging one match agree on it without a merge rule.
 */
export const KindMatchEnded: EventKind = "match_ended";
/**
 * CONTROL — the clock and the log's own bookkeeping. No buttons on a tab.
 * The clock is driven by these events rather than by device state, so it survives
 * a reload and two coaches tagging one match agree on it without a merge rule.
 */
export const KindZoneChanged: EventKind = "zone_changed";
/**
 * CONTROL — the clock and the log's own bookkeeping. No buttons on a tab.
 * The clock is driven by these events rather than by device state, so it survives
 * a reload and two coaches tagging one match agree on it without a merge rule.
 */
export const KindVoid: EventKind = "void";
/**
 * EventGroup is where a kind appears in the tagging screen.
 */
export type EventGroup =
	| "play"
	| "set_piece"
	| "discipline"
	| "score"
	| "control";
export const GroupPlay: EventGroup = "play";
export const GroupSetPiece: EventGroup = "set_piece";
export const GroupDiscipline: EventGroup = "discipline";
export const GroupScore: EventGroup = "score";
export const GroupControl: EventGroup = "control";
/**
 * CatalogueEntry is the configuration for one kind: what it is called, where it
 * appears, whether it belongs to a player, and what it is worth.
 * This is served to the client rather than hard-coded in the frontend, so adding
 * a kind is a data change and a redeploy of one binary — and so a second club can
 * eventually be given a different catalogue without a fork.
 */
export interface CatalogueEntry {
	kind: EventKind;
	label: string;
	group: EventGroup;
	player: boolean;
	points?: number /* int */;
}

//////////
// source: errors.go
/*
Package core holds the domain types and rules. It imports only the standard
library: no storage, no transport, no logging.
*/

/**
 * ValidationError describes a rejected field.
 */
export interface ValidationError {
	Field: string;
	Reason: string;
}

//////////
// source: event.go

/**
 * Zone is the part of the pitch play is in, seen from the tagging team's end. It
 * is a running toggle rather than a location tag on every event: time
 * accumulates in whichever zone is current, which yields a territory figure for
 * almost no tagging effort.
 */
export type Zone = "our_22" | "our_half" | "their_half" | "their_22";
export const ZoneOur22: Zone = "our_22";
export const ZoneOurHalf: Zone = "our_half";
export const ZoneTheirHalf: Zone = "their_half";
export const ZoneTheir22: Zone = "their_22";
/**
 * Possession is the other running toggle: who has the ball.
 */
export type Possession = "us" | "them";
export const PossessionUs: Possession = "us";
export const PossessionThem: Possession = "them";
/**
 * Payload keys. Payload values are always strings because the map round-trips
 * through JSON in two languages, and a number would arrive as a float64 on one
 * side and an int on the other.
 */
export const PayloadZone = "zone";
/**
 * Payload keys. Payload values are always strings because the map round-trips
 * through JSON in two languages, and a number would arrive as a float64 on one
 * side and an int on the other.
 */
export const PayloadPossession = "possession";
/**
 * Payload keys. Payload values are always strings because the map round-trips
 * through JSON in two languages, and a number would arrive as a float64 on one
 * side and an int on the other.
 */
export const PayloadOnPlayer = "onPlayerId";
/**
 * Payload keys. Payload values are always strings because the map round-trips
 * through JSON in two languages, and a number would arrive as a float64 on one
 * side and an int on the other.
 */
export const PayloadOffPlayer = "offPlayerId";
/**
 * Event is one immutable entry in a match's log. Nothing is ever mutated or
 * deleted: a mis-tap is cancelled by appending a void that references it, which
 * keeps every derived figure recomputable from scratch and leaves an audit trail
 * of what was corrected after the match.
 */
export interface Event {
	id: string;
	kind: EventKind;
	playerId?: string;
	clockMs: number /* int */;
	period: number /* int */;
	payload?: { [key: string]: string };
	deviceId: string;
	voidsId?: string;
}

//////////
// source: match.go

export type Venue = "home" | "away" | "neutral";
export const VenueHome: Venue = "home";
export const VenueAway: Venue = "away";
export const VenueNeutral: Venue = "neutral";
export type MatchStatus = "scheduled" | "in_progress" | "completed";
export const MatchScheduled: MatchStatus = "scheduled";
export const MatchInProgress: MatchStatus = "in_progress";
export const MatchCompleted: MatchStatus = "completed";
/**
 * LineupSlot ties a jersey number to the player wearing it.
 */
export interface LineupSlot {
	jersey: number /* int */;
	playerId: string;
}
/**
 * Lineup is the selected squad for one match.
 */
export interface Lineup {
	starters: LineupSlot[];
	bench: LineupSlot[];
}
export interface Match {
	id?: string;
	clubId?: string;
	teamId?: string;
	seasonId: string;
	opponent: string;
	kickoffAt: string;
	competition: string;
	venue: Venue;
	status: MatchStatus;
	lineup: Lineup;
}

//////////
// source: player.go

export type PlayerStatus = "active" | "inactive";
export const PlayerActive: PlayerStatus = "active";
export const PlayerInactive: PlayerStatus = "inactive";
export interface Player {
	id?: string;
	clubId?: string;
	firstName: string;
	lastName: string;
	dob: string;
	positions: Position[];
	teamIds: string[];
	status: PlayerStatus;
}

//////////
// source: position.go

/**
 * Position is an individual playing position. Thirteen positions cover the
 * fifteen starting jerseys: both locks wear 4 and 5, and both wings wear 11
 * and 14.
 */
export type Position =
	| "loosehead"
	| "hooker"
	| "tighthead"
	| "lock"
	| "blindside"
	| "openside"
	| "number_eight"
	| "scrum_half"
	| "fly_half"
	| "wing"
	| "inside_centre"
	| "outside_centre"
	| "fullback";
export const Loosehead: Position = "loosehead"; // 1
export const Hooker: Position = "hooker"; // 2
export const Tighthead: Position = "tighthead"; // 3
export const Lock: Position = "lock"; // 4, 5
export const Blindside: Position = "blindside"; // 6
export const Openside: Position = "openside"; // 7
export const NumberEight: Position = "number_eight"; // 8
export const ScrumHalf: Position = "scrum_half"; // 9
export const FlyHalf: Position = "fly_half"; // 10
export const Wing: Position = "wing"; // 11, 14
export const InsideCentre: Position = "inside_centre"; // 12
export const OutsideCentre: Position = "outside_centre"; // 13
export const Fullback: Position = "fullback"; // 15
/**
 * PositionGroup is the unit within which players are compared. Comparing a
 * prop's carry count against a winger's is noise, so rankings never cross a
 * group boundary.
 */
export type PositionGroup =
	| "front_row"
	| "second_row"
	| "back_row"
	| "half_backs"
	| "centres"
	| "back_three";
export const FrontRow: PositionGroup = "front_row";
export const SecondRow: PositionGroup = "second_row";
export const BackRow: PositionGroup = "back_row";
export const HalfBacks: PositionGroup = "half_backs";
export const Centres: PositionGroup = "centres";
export const BackThree: PositionGroup = "back_three";

//////////
// source: stats.go

/**
 * SliceDurationMs is the width of a time-slice bucket. ClockMs is continuous from
 * kick-off, so bucketing every metric into 20-minute blocks is one grouping here
 * and needs no extra data, no extra writes and no schema change.
 */
export const SliceDurationMs = 20 * 60 * 1000;
export interface Score {
	us: number /* int */;
	them: number /* int */;
}
/**
 * PlayerStats is one player's contribution to one match. Counts holds only
 * non-zero entries, so the Go and TypeScript folds serialise identically.
 */
export interface PlayerStats {
	playerId: string;
	jersey: number /* int */;
	position: Position;
	group: PositionGroup;
	onPitch: boolean;
	minutesMs: number /* int */;
	counts: Partial<Record<EventKind, number /* int */>>;
}
/**
 * Slice is one 20-minute block. Per-player slicing is deliberately absent: it is a
 * season-view concern and would multiply this structure by 23 for no reader.
 */
export interface Slice {
	fromMs: number /* int */;
	toMs: number /* int */;
	score: Score;
	territoryMs: Partial<Record<Zone, number /* int */>>;
	possessionMs: Partial<Record<Possession, number /* int */>>;
	counts: Partial<Record<EventKind, number /* int */>>;
}
/**
 * MatchState is the whole state of a match. It is derived, never stored as truth:
 * void an event, re-fold, and every number below is correct by construction.
 */
export interface MatchState {
	status: MatchStatus;
	period: number /* int */;
	clockMs: number /* int */;
	running: boolean;
	score: Score;
	zone: Zone;
	possession: Possession;
	territoryMs: Partial<Record<Zone, number /* int */>>;
	possessionMs: Partial<Record<Possession, number /* int */>>;
	counts: Partial<Record<EventKind, number /* int */>>;
	players: { [key: string]: PlayerStats };
	slices: Slice[];
	voidedIds: string[];
}
/**
 * PlayerMatchStats is the derived per-player document. It denormalises team,
 * season, player and date so a season trend or a squad comparison is a
 * collection-group query rather than a rollup table that can go stale.
 */
export interface PlayerMatchStats {
	playerId: string;
	matchId: string;
	teamId: string;
	seasonId: string;
	matchDate: string;
	jersey: number /* int */;
	position: Position;
	group: PositionGroup;
	minutesMs: number /* int */;
	counts: { [key: string]: number /* int */ };
}

//////////
// source: team.go

/**
 * Team is a squad that plays fixtures — the 1st XV, the Colts, the women's
 * side. Players belong to the club, not to a team, so one player can be in
 * several teams at once.
 */
export interface Team {
	id?: string;
	clubId?: string;
	name: string;
	shortName: string;
	active: boolean;
}
