// Code generated by cmd/gen-types. DO NOT EDIT.

import type { Position, PositionGroup } from "./core";

export const POSITIONS: readonly Position[] = [
	"loosehead",
	"hooker",
	"tighthead",
	"lock",
	"blindside",
	"openside",
	"number_eight",
	"scrum_half",
	"fly_half",
	"wing",
	"inside_centre",
	"outside_centre",
	"fullback",
];

export const POSITION_GROUPS: readonly PositionGroup[] = [
	"front_row",
	"second_row",
	"back_row",
	"half_backs",
	"centres",
	"back_three",
];

export const GROUP_OF_POSITION: Record<Position, PositionGroup> = {
	loosehead: "front_row",
	hooker: "front_row",
	tighthead: "front_row",
	lock: "second_row",
	blindside: "back_row",
	openside: "back_row",
	number_eight: "back_row",
	scrum_half: "half_backs",
	fly_half: "half_backs",
	wing: "back_three",
	inside_centre: "centres",
	outside_centre: "centres",
	fullback: "back_three",
};
