// Code generated by cmd/gen-types. DO NOT EDIT.

import type { Position, PositionGroup } from "./core";

export const POSITIONS: readonly Position[] = [
	"loosehead",
	"hooker",
	"tighthead",
	"lock",
	"blindside",
	"openside",
	"number_eight",
	"scrum_half",
	"fly_half",
	"wing",
	"inside_centre",
	"outside_centre",
	"fullback",
];

export const POSITION_GROUPS: readonly PositionGroup[] = [
	"front_row",
	"second_row",
	"back_row",
	"half_backs",
	"centres",
	"back_three",
];

export const GROUP_OF_POSITION: Record<Position, PositionGroup> = {
	loosehead: "front_row",
	hooker: "front_row",
	tighthead: "front_row",
	lock: "second_row",
	blindside: "back_row",
	openside: "back_row",
	number_eight: "back_row",
	scrum_half: "half_backs",
	fly_half: "half_backs",
	wing: "back_three",
	inside_centre: "centres",
	outside_centre: "centres",
	fullback: "back_three",
};

export const POSITION_OF_JERSEY: Record<number, Position> = {
	1: "loosehead",
	2: "hooker",
	3: "tighthead",
	4: "lock",
	5: "lock",
	6: "blindside",
	7: "openside",
	8: "number_eight",
	9: "scrum_half",
	10: "fly_half",
	11: "wing",
	12: "inside_centre",
	13: "outside_centre",
	14: "wing",
	15: "fullback",
};
