// Command gen-types narrows the TypeScript types that tygo generates.
//
// tygo renders a named Go string type as `export type Position = string`, which
// makes client-side exhaustiveness checks vacuous: Record<Position, string> would
// accept any object at all. This rewrites those aliases into real string-literal
// unions built from the Go constants, and emits the position-to-group mapping so
// the client never re-implements it.
//
// Run via `make types`, after tygo.
package main

import (
	"fmt"
	"os"
	"strings"

	"pitch-ai/internal/auth"
	"pitch-ai/internal/core"
)

const (
	corePath   = "web/src/types/core.ts"
	authPath   = "web/src/types/auth.ts"
	groupsPath = "web/src/types/groups.ts"
)

func main() {
	positions := strs(core.AllPositions())
	groups := strs(core.AllPositionGroups())
	statuses := []string{string(core.PlayerActive), string(core.PlayerInactive)}
	roles := strs(auth.AllRoles())

	if err := narrow(corePath, map[string][]string{
		"Position":      positions,
		"PositionGroup": groups,
		"PlayerStatus":  statuses,
		"Venue":         strs(core.AllVenues()),
		"MatchStatus":   strs(core.AllMatchStatuses()),
	}); err != nil {
		fail(err)
	}

	if err := narrow(authPath, map[string][]string{
		"Role":   roles,
		"Action": strs(auth.AllActions()),
	}); err != nil {
		fail(err)
	}

	if err := writeGroups(positions); err != nil {
		fail(err)
	}

	fmt.Println("gen-types: narrowed enums and wrote", groupsPath)
}

// narrow replaces `export type X = string;` with a string-literal union.
func narrow(path string, unions map[string][]string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading %s: %w", path, err)
	}
	out := string(raw)

	for name, values := range unions {
		alias := fmt.Sprintf("export type %s = string;", name)
		if !strings.Contains(out, alias) {
			return fmt.Errorf("%s: expected tygo to emit %q; did the Go type change?", path, alias)
		}
		out = strings.Replace(out, alias,
			fmt.Sprintf("export type %s = %s;", name, union(values)), 1)
	}

	out = dropAnyAliases(out)
	if err := assertNoWideAliases(path, out); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(out), 0o644)
}

// opaqueTypes are named Go string types that are deliberately left as `string`
// on the client because they have no fixed set of values — identifiers and the
// like. Anything not listed here must be narrowed into a union.
var opaqueTypes = map[string]bool{}

// assertNoWideAliases fails when a named string type reaches the client as
// `export type X = string`. Such an alias silently defeats exhaustiveness
// checks: Record<X, string> would accept any object at all. Adding an enum in
// Go and forgetting to register it above should break the build, not quietly
// produce a type that checks nothing.
func assertNoWideAliases(path, src string) error {
	var wide []string
	for line := range strings.Lines(src) {
		trimmed := strings.TrimSpace(line)
		name, ok := strings.CutPrefix(trimmed, "export type ")
		if !ok {
			continue
		}
		name, ok = strings.CutSuffix(name, " = string;")
		if !ok || opaqueTypes[name] {
			continue
		}
		wide = append(wide, name)
	}

	if len(wide) > 0 {
		return fmt.Errorf(
			"%s: %s reached the client as `= string`.\n"+
				"  Register each in cmd/gen-types (with an All…() accessor in Go) so it becomes a\n"+
				"  string-literal union, or add it to opaqueTypes if it genuinely has no fixed values.",
			path, strings.Join(wide, ", "))
	}
	return nil
}

// dropAnyAliases removes the `export type X = any;` lines tygo emits for Go
// interfaces. They carry no information for the client and trip Biome's
// noExplicitAny rule.
func dropAnyAliases(src string) string {
	var kept []string
	for line := range strings.Lines(src) {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "export type ") && strings.HasSuffix(trimmed, "= any;") {
			continue
		}
		kept = append(kept, line)
	}
	return strings.Join(kept, "")
}

// writeGroups emits the position-to-group lookup, so the client derives a
// player's comparison group from the same table Go uses.
func writeGroups(positions []string) error {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/gen-types. DO NOT EDIT.\n\n")
	b.WriteString(`import type { Position, PositionGroup } from "./core";` + "\n\n")

	b.WriteString("export const POSITIONS: readonly Position[] = [\n")
	for _, p := range positions {
		fmt.Fprintf(&b, "\t%q,\n", p)
	}
	b.WriteString("];\n\n")

	b.WriteString("export const POSITION_GROUPS: readonly PositionGroup[] = [\n")
	for _, g := range core.AllPositionGroups() {
		fmt.Fprintf(&b, "\t%q,\n", string(g))
	}
	b.WriteString("];\n\n")

	b.WriteString("export const GROUP_OF_POSITION: Record<Position, PositionGroup> = {\n")
	for _, p := range core.AllPositions() {
		fmt.Fprintf(&b, "\t%q: %q,\n", string(p), string(p.Group()))
	}
	b.WriteString("};\n")

	return os.WriteFile(groupsPath, []byte(b.String()), 0o644)
}

func union(values []string) string {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return strings.Join(quoted, " | ")
}

func strs[T ~string](in []T) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = string(v)
	}
	return out
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen-types:", err)
	os.Exit(1)
}
